### ISSUE TITLE
遍历出来的CheckBoxGroup应该怎么写全选？

### ISSUE THREAD

**Issue by ghost** [vueComponent/ant-design-vue-pro#1021]
**Question （问题描述）**
遍历出来的checkboxgroup应该怎么写全选？

**Additional context（附加信息）**
```
<template v-for="permission in permissions">
  <a-form-item
       class="permission-group"
       v-if="permission.actionsOptions && permission.actionsOptions.length > 0"
       :labelCol="labelCol"
       :wrapperCol="wrapperCol"
       :key="permission.permissionId"
       :label="permission.permissionName"
       >
       <a-checkbox :indeterminate="indeterminate" :checked="checkAll" @change="onCheckAllChange">全选</a-checkbox>
        <a-checkbox-group v-decorator="[`permissions.${permission.permissionId}`]" :options="permission.actionsOptions" :disabled="disabled" @change="onCheckBoxChange" />
  </a-form-item>
</template>
```
```
下面是照搬 ant-design-vue 官方文档，肯定是错的。
onCheckBoxChange (checkedList) {
      this.indeterminate = !!checkedList.length && checkedList.length < this.permission.actionsOptions.length
      this.checkAll = checkedList.length === this.permission.actionsOptions.length
},
onCheckAllChange (e) {
      Object.assign(this, {
      checkedList: e.target.checked ? this.permission.actionsOptions : [],
      indeterminate: false,
      checkAll: e.target.checked
})
```
this.permission 返回的数组
```
0:
actionEntitySet: Array(1)
actionList: Array(1)
actionsOptions: Array(1)
  0:
  defaultCheck: false
  label: "查看"
  value: "list"
dataAccess: null
permissionId: "dashboard"
permissionName: "控制面板"
roleId: "控制面板"
1: {…}
2: {…}
```
像这样 options 应该怎么设置？
