### ISSUE TITLE
暗色模式

### ISSUE THREAD

**Issue by 88xu** [vueComponent/ant-design-vue-pro#1401]
作者你好，这个暗色模式不能直接开启吗，需要什么条件才能开启暗色模式

**Comment by kovsu** [comment]
在 vueuse 里面，实现这个 dark 模式切换，他是给 html 标签加了一个 class 叫 `dark`。然后你还需要给他设置样式
```css
html.dark {
  color-scheme: dark;
}
```
这样就实现了 dark 模式，切换成 light 模式的话，就没有这个 叫 dark 的 className。
所以我猜可能在这里面，也是这样去实现的
