### ISSUE TITLE
在Iphone上， 手指按在表格区域无法滚动屏幕

### ISSUE THREAD

**Issue by xs06974** [vueComponent/ant-design-vue-pro#189]
如题。可用iphone打开https://preview.pro.loacg.com/list/table-list   进行重现；

我知道ant-design本身也解释过它不是针对移动设备打造的，但我觉得ant-design-pro-vue在移动设备上表现还不错，故而提出此bug。

**Comment by sendya** [comment]
该功能无法修正，如果你确实要在上面滚动，可以移除以下代码：

```less
    /**
     * ant-table-wrapper
     * 覆盖的表格手机模式样式，如果想修改在手机上表格最低宽度，可以在这里改动
     */
    .ant-table-wrapper {
      .ant-table-content {
        overflow-y: auto;
      }
      .ant-table-body {
        min-width: 800px;
      }
    }
```

所在文件 https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/global.less#L35-L42
