### ISSUE TITLE
右侧滚动条不太对劲的说？

### ISSUE THREAD

**Issue by yihuishou** [vueComponent/ant-design-vue-pro#4]
灰色的滚动条连登陆页都有的说~

**Comment by sendya** [comment]
故意开的，可以关闭;

https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/layout/LayoutMain.vue#L103

```css
  body {
    // 打开滚动条固定显示
    overflow-y: scroll;
  }
```
